# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devc < Formula
  desc "AI-safe development containers with devcontainer.json support"
  homepage "https://github.com/sxwebdev/devc"
  version "0.2.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sxwebdev/devc/releases/download/v0.2.0/devc_darwin_amd64.tar.gz"
      sha256 "067c323d6bb4193c37de730b65523788212a2bdbc8d3db610f683851883ec7d0"

      define_method(:install) do
        bin.install "devc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sxwebdev/devc/releases/download/v0.2.0/devc_darwin_arm64.tar.gz"
      sha256 "387fd3d67ba0de82335fe4c927919f9ca7528014fefd59fc6aad366172af5980"

      define_method(:install) do
        bin.install "devc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxwebdev/devc/releases/download/v0.2.0/devc_linux_amd64.tar.gz"
      sha256 "2ac8a59c298aff69d390faae6c267dfe4e348a4e2a958dc10fe505e336731b7c"
      define_method(:install) do
        bin.install "devc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxwebdev/devc/releases/download/v0.2.0/devc_linux_arm64.tar.gz"
      sha256 "9f55cc535b82f66e552bf2c43a37475023bde4ce5b9e382d25e31a64f1dd69b1"
      define_method(:install) do
        bin.install "devc"
      end
    end
  end

  test do
    system "#{bin}/devc", "--help"
  end
end
