# typed: false
# frozen_string_literal: true

# This file is generated by GoReleaser. DO NOT EDIT.
class Devc < Formula
  desc "AI-safe development containers with devcontainer.json support"
  homepage "https://github.com/sxwebdev/devc"
  version "2026.03.31"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sxwebdev/devc/releases/download/v2026.03.31/devc_darwin_amd64.tar.gz"
      sha256 "1ecb2e8f4961b43ff807e3d36bdc9919b2807ae7e8baebfb8f16214a40687259"
    end

    on_arm do
      url "https://github.com/sxwebdev/devc/releases/download/v2026.03.31/devc_darwin_arm64.tar.gz"
      sha256 "6acd73c9bd3ced06766dfa83cd114a6241e18787cd459e859384eabd7655c995"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sxwebdev/devc/releases/download/v2026.03.31/devc_linux_amd64.tar.gz"
      sha256 "ae779020c1fd65e419f604ab1938dbe561d6e30b6d36d3fabb9c83bd49ec98ea"
    end

    on_arm do
      url "https://github.com/sxwebdev/devc/releases/download/v2026.03.31/devc_linux_arm64.tar.gz"
      sha256 "08383be617e1d7baa94f61507b249ed70d725fc0aee8960d88dea190e7db9dbf"
    end
  end

  depends_on "docker" => :optional

  def install
    bin.install "devc"
  end

  test do
    system "#{bin}/devc", "--help"
  end
end

