# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devc < Formula
  desc "AI-safe development containers with devcontainer.json support"
  homepage "https://github.com/sxwebdev/devc"
  version "0.1.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sxwebdev/devc/releases/download/v0.1.0/devc_darwin_amd64.tar.gz"
      sha256 "b7a43d387a909371ad07bc61566fbef13dfdd0ab8f135d09db906a6917112b1a"

      define_method(:install) do
        bin.install "devc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sxwebdev/devc/releases/download/v0.1.0/devc_darwin_arm64.tar.gz"
      sha256 "504eb7a6eb5404f9a883cc0a49377622528cbdd62bae527f06a32d7478395a44"

      define_method(:install) do
        bin.install "devc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxwebdev/devc/releases/download/v0.1.0/devc_linux_amd64.tar.gz"
      sha256 "db95dbb11018e59ba7bbb4b81b6440d8a275bcac14105e2de72675973bd61985"
      define_method(:install) do
        bin.install "devc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxwebdev/devc/releases/download/v0.1.0/devc_linux_arm64.tar.gz"
      sha256 "ddabb31d22a2f52b661876b943e730e9580415706f612c6a8d6f2021d99c4a6a"
      define_method(:install) do
        bin.install "devc"
      end
    end
  end

  test do
    system "#{bin}/devc", "--help"
  end
end
